#!/bin/bash
#PBS -l nodes=1:ppn=1,vmem=32g,walltime=01:00:00
#PBS -N app-wmc_figures
#PBS -V

rm -rf images
rm -rf images.json

singularity exec -e --nv docker://brainlife/dipy:1.4.1 python3 ./main.py
